version: "3.8"
services:
    matcher:
        build:
            context: ./
        container_name: matcher
        ports:
            - 5000:5000
        depends_on:
            - rabbitmq
        environment:
            - AMQP_ENDPOINT=amqp://guest:guest@rabbitmq:5672

    rabbitmq:
        image: rabbitmq:3.11-alpine
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        restart: always
