version: "3.8"
services:
    matcher:
        build:
            context: ./
        container_name: matcher
        ports:
            - 5000:5000
        environment:
            - AMQP_ENDPOINT=amqp://guest:guest@rabbitmq:5672
            - API_URL=http://api:8000
            - ITEMS_URL=mongodb://user:password@mongo:27017/lf?authSource=admin
        networks:
            - lf-dev

networks:
    lf-dev:
        external: true
